name: quill_format
description: Simple and expressive format for describing rich-text content created for Quill.js editor.
version: 1.0.2
homepage: https://github.com/glynskyi/quill-format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.8
  pedantic: ^1.11.0
