name: quill_format
description: Simple and expressive format for describing rich-text content created for Quill.js editor.
version: 1.0.3
homepage: https://github.com/glynskyi/quill-format

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  quill_delta: ^3.0.0-nullsafety.2

dev_dependencies:
  test: ^1.17.8
  pedantic: ^1.11.0
